package ec.com.sisapus.modelo;
// Generated 18/01/2015 05:06:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rubro generated by hbm2java
 */
public class Rubro  implements java.io.Serializable {


     private Integer codigoRubro;
     private Categoriarubro categoriarubro;
     private Usuario usuario;
     private String nombreRubro;
     private String detalleRubro;
     private String unidadRubro;
     private Set analisispreciounitarios = new HashSet(0);

    public Rubro() {
        this.codigoRubro = 0;
        this.categoriarubro = new Categoriarubro();
        this.usuario=new Usuario();
    }

    public Rubro(Categoriarubro categoriarubro, Usuario usuario, String nombreRubro, String detalleRubro, String unidadRubro, Set analisispreciounitarios) {
       this.categoriarubro = categoriarubro;
       this.usuario = usuario;
       this.nombreRubro = nombreRubro;
       this.detalleRubro = detalleRubro;
       this.unidadRubro = unidadRubro;
       this.analisispreciounitarios = analisispreciounitarios;
    }
   
    public Integer getCodigoRubro() {
        return this.codigoRubro;
    }
    
    public void setCodigoRubro(Integer codigoRubro) {
        this.codigoRubro = codigoRubro;
    }
    public Categoriarubro getCategoriarubro() {
        return this.categoriarubro;
    }
    
    public void setCategoriarubro(Categoriarubro categoriarubro) {
        this.categoriarubro = categoriarubro;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombreRubro() {
        return this.nombreRubro;
    }
    
    public void setNombreRubro(String nombreRubro) {
        this.nombreRubro = nombreRubro;
    }
    public String getDetalleRubro() {
        return this.detalleRubro;
    }
    
    public void setDetalleRubro(String detalleRubro) {
        this.detalleRubro = detalleRubro;
    }
    public String getUnidadRubro() {
        return this.unidadRubro;
    }
    
    public void setUnidadRubro(String unidadRubro) {
        this.unidadRubro = unidadRubro;
    }
    public Set getAnalisispreciounitarios() {
        return this.analisispreciounitarios;
    }
    
    public void setAnalisispreciounitarios(Set analisispreciounitarios) {
        this.analisispreciounitarios = analisispreciounitarios;
    }




}


